defaults:
        - wandb : defaults
        - dataset: cifar10
        - train_and_test: default
        - model : dummy #dummy #ddpm_unet_mega_downscaled # dummy_giant # dummy 
        - visualization: visualize
        - optimizer: adam
        - loss: implicit_sm # entropy, mse